/*
Problem: Write an algorithm to determine if a number n is happy.
A happy number is a number defined by the following process:
Starting with any positive integer, replace the number by the sum of the squares of its digits.
Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
Those numbers for which this process ends in 1 are happy.
Return true if n is a happy number, and false if not.

Example 1:
Input: n = 19
Output: true
Explanation:
12 + 92 = 82
82 + 22 = 68
62 + 82 = 100
12 + 02 + 02 = 1

Example 2:
Input: n = 2
Output: false
 

Constraints: 1 <= n <= 231 - 1

Link: https://leetcode.com/problems/happy-number/description/?envType=study-plan-v2&envId=top-interview-150

*/

#include <bits/stdc++.h>
using namespace std;


// ---------------- Better Approach ----------------

/*
Intuition: A happy number eventually reaches 1 when repeatedly replaced by the 
sum of the squares of its digits. If a number repeats, a cycle is formed and
the number can never reach 1.

Approach:
1. Use a hash set to store all previously seen numbers.
2. Repeatedly calculate the sum of the squares of the digits.
3. If the result becomes 1, return true.
4. If the result has already been seen, a cycle exists, so return false.
5. Otherwise, insert the result into the set and contnue.

Time Complexity: O(log n)

Space Complexity: O(k) where k is the number of distinct values encountered 
                  before reaching 1 or entering a cycle.
*/

class BetterSolution {
public:
    bool isHappy(int n) {
        unordered_set<int> seen;
        seen.insert(n);

        while(n != 1){
            int ans = 0;

            while(n){
                int m = n%10;
                n = n/10;
                ans += m*m;
            }
            if(seen.count(ans)) return false;

            seen.insert(ans);            
            n = ans;
        }

        return true;
    }
};




// ---------------- Optimal Approach ----------------

/*
Intuition: The sequence generated by repeatedly replacing a number with the 
sum of the squares of its digits either reaches 1 or enters a cycle. This can
be treated as a cycle detection problem and solved using Floyd's Cycle Detection
Algorithm.

Approach:
1. Define a helper function to compute the sum of squares of digits of a number.
2. Use 2 pointers:
   - slow moves one step at a time.
   - fast moves two steps at a time.
3. If fast reaches 1, the number is happy.
4. If slow and fast meet, a cycle exists, so the number is not happy.
5. Return whether fast becomes 1.

Time Complexity: O(log n)

Space Complexity: O(1)
*/

class OptimalSolution {
public:
    int getAns(int n){
        int ans = 0;
        while(n){
            int digit = n%10;
            ans += digit*digit;
            n = n/10;
        }
        return ans;
    }

    bool isHappy(int n) {
        int slow = n;
        int fast = getAns(n);

        while(fast != 1 && fast != slow){
            slow = getAns(slow);
            fast = getAns(getAns(fast));
        }

        return fast==1;
    }
};


// ========================================================
//                         Main
// ========================================================

int main() {

    BetterSolution better;
    OptimalSolution optimal;

    int n = 19;

    cout << "Input: " << n << endl;

    cout << "Better Solution: "
         << (better.isHappy(n) ? "true" : "false") << endl;

    cout << "Optimal Solution: "
         << (optimal.isHappy(n) ? "true" : "false") << endl;
    
    return 0;
}